[package]
name = "oreos"
version = "0.1.0"
authors = ["Vyacheslav Pukhanov <vyacheslav.pukhanov@gmail.com>"]
edition = "2018"

[dependencies]
bootloader = "0.9.5"
volatile = "0.2.6"
spin = "0.5.2"

[dependencies.lazy_static]
version = "1.4.0"
features = ["spin_no_std"]